export const ActionTypes = {
  //USER ACTION
  SET_USERS: "SET_USERS",
  SELECTED_USER: "SELECTED_USER",
  ADD_USER: "ADD_USER",
  UPDATE_SELECTED_USER: "UPDATE_SELECTED_USER",
  REMOVE_SELECTED_USER: "REMOVE_SELECTED_USER",
};
